spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_companies
    username: postgres
    password: prod.123
    auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect